// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2fT_wp_OpdFZ54v8aqMpUpFWG7Oj-110',
    appId: '1:225466977496:web:219a4c6156984081e09bad',
    messagingSenderId: '225466977496',
    projectId: 'project-5-62c33',
    authDomain: 'project-5-62c33.firebaseapp.com',
    storageBucket: 'project-5-62c33.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnj4RMa-DW0D28cvIda4nFNMsPHyyYlIA',
    appId: '1:225466977496:android:6cb7c5b22bda4009e09bad',
    messagingSenderId: '225466977496',
    projectId: 'project-5-62c33',
    storageBucket: 'project-5-62c33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4o_F4JvqLhtVw7YhMJ4muMKYlkCIGihM',
    appId: '1:225466977496:ios:cfd73429b809aa95e09bad',
    messagingSenderId: '225466977496',
    projectId: 'project-5-62c33',
    storageBucket: 'project-5-62c33.firebasestorage.app',
    iosBundleId: 'com.example.project5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4o_F4JvqLhtVw7YhMJ4muMKYlkCIGihM',
    appId: '1:225466977496:ios:cfd73429b809aa95e09bad',
    messagingSenderId: '225466977496',
    projectId: 'project-5-62c33',
    storageBucket: 'project-5-62c33.firebasestorage.app',
    iosBundleId: 'com.example.project5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2fT_wp_OpdFZ54v8aqMpUpFWG7Oj-110',
    appId: '1:225466977496:web:a3664ac4c15cbfcae09bad',
    messagingSenderId: '225466977496',
    projectId: 'project-5-62c33',
    authDomain: 'project-5-62c33.firebaseapp.com',
    storageBucket: 'project-5-62c33.firebasestorage.app',
  );
}
